"""Typed offline exchange and market-event ports."""
from __future__ import annotations
from typing import Protocol, runtime_checkable

@runtime_checkable
class ExchangePort(Protocol):
    def submit_order(self, request): ...
    def cancel_order(self, client_order_id: str): ...
    def read_order(self, client_order_id: str): ...
    def read_fills(self, client_order_id: str | None = None): ...
    def read_positions(self, symbol: str | None = None): ...
    def read_open_orders(self): ...
    def read_balance(self): ...

@runtime_checkable
class MarketEventPort(Protocol):
    def apply_market_event(self, event): ...
